/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lsystem.gui.animations;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;

/**
 *
 * @author Jacob Cohen
 */
public class TimerSettingsPanel extends javax.swing.JPanel {
	private static final long serialVersionUID = 7791330426829659876L;
	
	/**
     * Creates new form TimerSettingsPanel
     */
    public TimerSettingsPanel(Font font, Color fontColor) {
        initComponents(font, fontColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(Font font, Color fontColor) {
    	this.setOpaque(false);
    	
        actionSpeedPanel = new javax.swing.JPanel();
        actionSpeedLabel = new javax.swing.JLabel();
        actionSpeedSlider = new javax.swing.JSlider();
        delayTimePanel = new javax.swing.JPanel();
        delayTimeLabel = new javax.swing.JLabel();
        delayTimeSlider = new javax.swing.JSlider();
        
        actionSpeedSlider.setMinimum(1);
        actionSpeedSlider.setMaximum(1000);
        actionSpeedSlider.setValue(1000);
        actionSpeedSlider.setMajorTickSpacing(10);
        
        delayTimeSlider.setMinimum(1);
        delayTimeSlider.setMaximum(1000);
        delayTimeSlider.setValue(1000);
        delayTimeSlider.setMajorTickSpacing(10);
        
        actionSpeedPanel.setOpaque(false);
        delayTimePanel.setOpaque(false);
        
        delayTimeSlider.setFocusable(false);
        actionSpeedSlider.setFocusable(false);
        
        GridLayout layout = new GridLayout(4, 1);
        layout.setVgap(0);
        layout.setHgap(0);
        setLayout(layout);
        
        actionSpeedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actionSpeedLabel.setText("Action Speed");
        actionSpeedLabel.setFont(font);
        actionSpeedLabel.setForeground(fontColor);
        actionSpeedPanel.add(actionSpeedLabel);
        actionSpeedPanel.add(actionSpeedSlider);
        
        delayTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delayTimeLabel.setText("Delay Time");
        delayTimeLabel.setFont(font);
        delayTimeLabel.setForeground(fontColor);
        delayTimePanel.add(delayTimeLabel);
        delayTimePanel.add(delayTimeSlider);
        
        add(actionSpeedLabel);
        add(actionSpeedSlider);
        add(delayTimeLabel);
        add(delayTimeSlider);

    }// </editor-fold>
    
    public Dimension getPreferredSize()
    {
    	return new Dimension(400, 150);
    }
    
    public int getActionSpeed()
    {
    	return actionSpeedSlider.getValue();
    }
    
    public int getDelayTime()
    {
    	return delayTimeSlider.getValue();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel actionSpeedLabel;
    private javax.swing.JPanel actionSpeedPanel;
    private javax.swing.JSlider actionSpeedSlider;
    private javax.swing.JLabel delayTimeLabel;
    private javax.swing.JPanel delayTimePanel;
    private javax.swing.JSlider delayTimeSlider;
    // End of variables declaration                   
}

