/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lsystem.gui.animations;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Jacob Cohen
 */
public class TimerSettingsPanel extends javax.swing.JPanel {
	private static final long serialVersionUID = 7791330426829659876L;
	
	/**
     * Creates new form TimerSettingsPanel
     */
    public TimerSettingsPanel(Font font, Color fontColor) {
        initComponents(font, fontColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(Font font, Color fontColor) {
    	this.setOpaque(false);
    	
        actionSpeedPanel = new javax.swing.JPanel();
        actionSpeedLabel = new javax.swing.JLabel();
        actionSpeedSlider = new javax.swing.JSlider();
        delayTimePanel = new javax.swing.JPanel();
        delayTimeLabel = new javax.swing.JLabel();
        delayTimeSlider = new javax.swing.JSlider();
        
        actionSpeedSlider.setMinimum(1);
        actionSpeedSlider.setMaximum(10000);
        actionSpeedSlider.setValue(1000);
        
        delayTimeSlider.setMinimum(1);
        delayTimeSlider.setMaximum(10000);
        delayTimeSlider.setValue(1000);
        
        actionSpeedPanel.setOpaque(false);
        delayTimePanel.setOpaque(false);
        
        delayTimeSlider.setFocusable(false);
        actionSpeedSlider.setFocusable(false);

        setLayout(new java.awt.GridLayout(2, 1));

        actionSpeedPanel.setLayout(new java.awt.BorderLayout());

        actionSpeedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actionSpeedLabel.setText("Action Speed");
        actionSpeedLabel.setFont(font);
        actionSpeedLabel.setForeground(fontColor);
        actionSpeedPanel.add(actionSpeedLabel, java.awt.BorderLayout.PAGE_START);
        actionSpeedPanel.add(actionSpeedSlider, java.awt.BorderLayout.CENTER);

        add(actionSpeedPanel);

        delayTimePanel.setLayout(new java.awt.BorderLayout());

        delayTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delayTimeLabel.setText("Delay Time");
        delayTimeLabel.setFont(font);
        delayTimeLabel.setForeground(fontColor);
        delayTimePanel.add(delayTimeLabel, java.awt.BorderLayout.PAGE_START);
        delayTimePanel.add(delayTimeSlider, java.awt.BorderLayout.CENTER);

        add(delayTimePanel);
    }// </editor-fold>        
    
    public int getActionSpeed()
    {
    	return actionSpeedSlider.getValue();
    }
    
    public int getDelayTime()
    {
    	return delayTimeSlider.getValue();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel actionSpeedLabel;
    private javax.swing.JPanel actionSpeedPanel;
    private javax.swing.JSlider actionSpeedSlider;
    private javax.swing.JLabel delayTimeLabel;
    private javax.swing.JPanel delayTimePanel;
    private javax.swing.JSlider delayTimeSlider;
    // End of variables declaration                   
}

